# these are the things that our rosprofile client will read and determine what it will inspect
hosts: 
    "192.168.1.149": False
    #     - "listen"
    #     - "profile"
    "SEF-PA144858":
        # - "talk"
        - "t"

topics:
    - "chatter"

# namespaces:
#     - ""

sampleRate: 0.2
updateRate: 2